language: node_js
node_js: 10

script:
  - npm install
  - npm run compile

before_deploy:
  - npm install -g vsce
  - vsce package

deploy:
  - provider: releases
    api_key:
      secure: "GKdHoqNUfRjAuCxvNFjCEj18F5ZI+8FAJHGeJoJKwB5pUPUN6VyxIzwUlX7t4pxArl1yW6OR1qPT9KCY2cd3oGMtr05iAXoUg/bYuuJTDPUbYldQMvetzz0PqIp6LLH1bHtRGElE65IeScKAjvD0/3UirwbBYhpJTWZbM06nq4BcLtn6ILSZuMDWZULi1jjSmDARWnkdWwvf3rFv4qAlgEf24K+fx77dHgl9ATorHyZfjikJznTSQTO0jV9WFltkP33rVEM2JROl2ODD1196Kkl98QhtPnLvrdHfX/0JMfwEqPGQInrkKAQvOWeYtQmxX8anovQfBeOxYJi/k74GvJCw1kVzewKDhUXqSN2Z4DtMngDlwa9sqEJKtPP4+MFUBvx2vsmoDS/0qnBPCmSujpTYq0SBC4snBoq8Lb8kTTEcuZLCTu726GYbPjeuEXXDbuDDYNxX4dG8DwQNTZhGdMnHWp2q6hYxkuhfuw9f1cBBYN5xWlcsz6Cln8rDSJgukHTUV2ZCPOQam8W84RcxYhBHbctlFzVPQL3KWq04yHrISQLR5KoC+tPTQWuHplbGM7jcCdgVsE4kLpL5aOd2mEFgqOF9PaQFAtAAo/7lfcS0GVb66SfDa+vOoN+6vz7arjIN+H93yXQ7UyyEhUGnM20JVXAklN/7XhIpxqRagUg="
    file: "*.vsix"
    file_glob: true
    skip_cleanup: true
    name: "Version $TRAVIS_TAG"
    on:
      tags: true
      repo: fwcd/vscode-kotlin-ide
  - provider: script
    script: vsce publish -p $VSC_TOKEN
    on:
      tags: true
      repo: fwcd/vscode-kotlin-ide
    
